import type { PayslipLine } from '@/types';

// Default Luxembourg monthly payroll template (editable)
// Codes and labels are chosen to match the calculators and line mapping in CreatePayslip
export const DEFAULT_LU_TEMPLATE: PayslipLine[] = [
  // Earnings
  {
    id: 'tpl-earn-1',
    code: 'SAL-BASE',
    label_fr: 'Salaire de base',
    label_en: 'Base salary',
    quantity: 1,
    rate: 0,
    amount: 0,
    type: 'earning',
  },
  {
    id: 'tpl-earn-2',
    code: 'GROSS',
    label_fr: 'Salaire brut',
    label_en: 'Gross Salary',
    quantity: 1,
    rate: 0,
    amount: 0,
    type: 'earning',
  },

  // Employee deductions
  {
    id: 'tpl-ee-1',
    code: 'EE_MALADIE',
    label_fr: 'Cotisation maladie employé',
    label_en: 'Employee Health Contribution',
    quantity: 1,
    rate: 0,
    amount: 0,
    type: 'deduction',
  },
  {
    id: 'tpl-ee-2',
    code: 'EE_PENSION',
    label_fr: 'Cotisation pension employé',
    label_en: 'Employee Pension Contribution',
    quantity: 1,
    rate: 0,
    amount: 0,
    type: 'deduction',
  },
  {
    id: 'tpl-ee-3',
    code: 'EE_CI_CO2',
    label_fr: 'CI-CO2',
    label_en: 'CI-CO2',
    quantity: 1,
    rate: 0,
    amount: 0,
    type: 'deduction',
  },
  {
    id: 'tpl-ee-4',
    code: 'EE_CIS',
    label_fr: 'CIS',
    label_en: 'CIS',
    quantity: 1,
    rate: 0,
    amount: 0,
    type: 'deduction',
  },
  {
    id: 'tpl-ee-5',
    code: 'EE_CISSM',
    label_fr: 'CISSM',
    label_en: 'CISSM',
    quantity: 1,
    rate: 0,
    amount: 0,
    type: 'deduction',
  },
  {
    id: 'tpl-ee-6',
    code: 'TAX',
    label_fr: 'Impôt sur le revenu',
    label_en: 'Income Tax',
    quantity: 1,
    rate: 0,
    amount: 0,
    type: 'deduction',
  },

  // Employer contributions
  {
    id: 'tpl-er-1',
    code: 'ER_MALADIE',
    label_fr: 'Cotisation maladie employeur',
    label_en: 'Employer Health Contribution',
    quantity: 1,
    rate: 0,
    amount: 0,
    type: 'employer_contrib',
  },
  {
    id: 'tpl-er-2',
    code: 'ER_PENSION',
    label_fr: 'Cotisation pension employeur',
    label_en: 'Employer Pension Contribution',
    quantity: 1,
    rate: 0,
    amount: 0,
    type: 'employer_contrib',
  },
  {
    id: 'tpl-er-3',
    code: 'ER_SANTE',
    label_fr: 'Santé (employeur)',
    label_en: 'Employer Healthcare',
    quantity: 1,
    rate: 0,
    amount: 0,
    type: 'employer_contrib',
  },
  {
    id: 'tpl-er-4',
    code: 'ER_ACCIDENT',
    label_fr: 'Assurance accident',
    label_en: 'Employer Accident Insurance',
    quantity: 1,
    rate: 0,
    amount: 0,
    type: 'employer_contrib',
  },
];